name: rdp
on:
  push:
    branches: [ main ]
jobs:
  Booting--:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Updating & Cleaning ..
        run: cd ; sudo apt clean &&  sudo rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && sudo apt update
      - name: Installing Gotty Web Terminal ..
        run:  sudo curl -sSL "https://github.com/yudai/gotty/releases/download/v1.0.1/gotty_linux_amd64.tar.gz" -o gotty.tar.gz ; sudo tar -xzvf gotty.tar.gz ; sudo rm gotty.tar.gz ; sudo mv gotty /usr/bin
      - name: Beautifying The Terminal ..
        run: cd && export TERM=xterm && rm .bashrc && echo $(curl -sSL "https://raw.githubusercontent.com/ammar0xff/tmp/main/.github/workflows/.bashrc") > .bashrc ; source .bashrc
      - name: Running Gotty Web Terminal On Port 8080 ..
        run: gotty -w /bin/bash &
      - name: Installing Rclone ..
        run: sudo apt install rclone
      - name: Installing Ngrok ..
        run: sudo curl -sSL "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz" -o ngrok.tgz ; sudo tar -xzvf ngrok.tgz ; sudo rm ngrok.tgz ; sudo mv ngrok /usr/bin
      - name: Configuring Ngrok Token ..
        run: ngrok config add-authtoken 2W7XbyEnUKx9YnLjW0vSdVHnFno_5AFGsMt2PTRTucTDVxzV9
      - name: Running Ngrok ..   
        run: ngrok http --domain=square-ant-gentle.ngrok-free.app 8080
