name: Ubuntu-Latest
on: workflow_dispatch
jobs:
  system:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Updating & Cleaning ..
        run: cd ; sudo apt clean &&  sudo rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && sudo apt update
      - name: Installing Gotty Web Terminal ..
        run:  sudo curl -sSL "https://github.com/yudai/gotty/releases/download/v1.0.1/gotty_linux_amd64.tar.gz" -o gotty.tar.gz ; sudo tar -xzvf gotty.tar.gz ; sudo rm gotty.tar.gz ; sudo mv gotty /usr/bin
      - name: Beautifying The Terminal ..
        run: TERM=xterm && rm .bashrc && git clone "https://github.com/ammar0xff/My-Lettel-Servers" && mv My-Lettel-Servers/.github/workflows/.bashrc . && source .bashrc && source ~/.bashrc
      - name: Running Gotty Web Terminal On Port 8080 ..
        run: export TERM=xterm && cd && gotty -w /bin/bash &
      - name: Installing Ngrok ..
        run: sudo curl -sSL "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz" -o ngrok.tgz ; sudo tar -xzvf ngrok.tgz ; sudo rm ngrok.tgz ; sudo mv ngrok /usr/bin
      - name: Configuring Ngrok Token ..
        run: ngrok config add-authtoken ${{ secrets.NGROK_TOKEN }}
      - name: Running Ngrok ..   
        run: ngrok http --domain=${{secrets.NGROK_DOMAIN}} 8080
